filme/urls.py
#para cada pagina precisa de 3 coisas
#url - view - template --- Sempre essas 3 coisas!
from django.urls import path
from .views import  Homefilmes, Homepage, Seriefilmes, Detalhesfilme, Detalhesserie

app_name = 'filme'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('filmes', Homefilmes.as_view(), name='homefilmes' ),
    path('serie', Seriefilmes.as_view(), name='seriefilmes'),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name='detalhesfilme'),
    path('serie/<int:pk>', Detalhesserie.as_view(), name='detalhesserie')
    ]

hashflix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme')),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
"""AQui no models é onde o python conversa, cria e armazena informações no BD"""

from django.db import models
from django.utils import timezone

# Create your models here.

LISTA_CATEGORIAS = (
    ("ANALISES", "Ánalises"),
    ("PROGRAMACAO", "Programacao"),
    ("APRESENTACAO", "Apresentação"),
    ("OUTROS", "Outros"),
)

LISTA_SEXO = (
    ("MASCULIO",'Masculino'),
    ("FEMININO","Feminino"),
)
#criar filme
class Filme(models.Model):
    thumb = models.ImageField(upload_to='thumb_filmes')
    titulo = models.CharField(max_length=100)
    descrição = models.TextField(max_length=1000)
    categoria =models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criação = models.DateTimeField(default= timezone.now)

    def __str__(self):
        return self.titulo

#criar episodios
class Seriado(models.Model):
    thumb = models.ImageField(upload_to='thumb_filmes')
    titulo = models.CharField(max_length=100)
    descrição = models.TextField(max_length=1000)
    categoria =models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criação = models.DateTimeField(default= timezone.now)

    def __str__(self):
        return self.titulo

#criar usuario
class Usuario(models.Model):
    nome = models.CharField(max_length=80)
    email = models.EmailField(unique=True)
    usuario = models.CharField(max_length=20, unique=True)
    sexo = models.CharField(max_length=8, choices=LISTA_SEXO)

    def __str__(self):
        return self.usuario
    
class Episodio(models.Model):
    filme = models.ForeignKey("Filme", related_name='episodios', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
        return self.filme.titulo + " - " + self.titulo

filme/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from .models import Filme, Seriado
from django.views.generic import TemplateView, ListView, DetailView

# Create your views here.

#def homepage(request):
#    return render(request, "homepage.html" )

class Homepage(TemplateView):
    template_name = 'homepage.html'

"""
def homefilmes(request):
    context = {}
    lista_filmes = Filme.objects.all #aqui pegou todos os filmes do banco de dados usando a classe Filme
    context['lista_filmes'] = lista_filmes
    return render(request, "homefilmes.html", context)
"""
class Homefilmes(ListView):
    template_name = "homefilmes.html"
    model = Filme #quando usa class para uma lista o padrão é object_lis, precisa trocar no html do filmes

class Detalhesfilme(DetailView):
    template_name = 'detalhefilmes.html'
    model = Filme

    def get(self, request, *args, **kwargs):
        filme = self.get_object()
        filme.visualizacoes += 1
        filme.save()
        return super(Detalhesfilme, self).get(request, *args, **kwargs) #redireciona o usuario para uma url final

    def get_context_data(self, **kwargs):
        context =  super(Detalhesfilme, self).get_context_data(**kwargs)
        # filtrar a minha tabela de filmes, pegando os filmes cuja categoria é igual a categoria do filme da página (object)
        filmes_relacionados = Filme.objects.filter(categoria=self.get_object().categoria) [0:5]
        context["filmes_relacinados"] = filmes_relacionados
        return context

class Seriefilmes(ListView):
    template_name = "seriefilmes.html"
    model = Seriado

class Detalhesserie(DetailView):
    template_name = 'detalheseries.html'
    model = Seriado

filme/templates/detalhefilmes.html
{% extends 'base.html' %}
{% block titulo %}
HomeFilmes HasheFlix
{% endblock %}
{% load static %}

{% block content %}

<main class="bg-primary_black min-h-screen w-full">
    <section class="h-screen relative bg-no-repeat pb-8 pl-16 flex items-end bg-cover" style="...">
        <div>
            <h2 class="text-6xl font-semibold tex_write my-4">
                {{object.titulo}}
            </h2>
            <p class="w-11/12 md:w-5/12 font-medium text-white my-4">
                {{object.descrição}}
            </p>
            <div class="flex my-4">
                <a href="#">
                    <button class="flex items-center bg-white px-5 rounded-md text-black" style="...">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>        
    </section>
    <section class="bg-primary_black flex justify-center py-10">
        <div class="p-8 w-10/12 relative">
            <h2 class="text-gray-200 text-3xl font-medium">
                {{object.descrição}}
            </h2>
            <div class="flex-justify-left items-center min-w-full movie_lis">
                <p class="text-gray-200 text-3xl font-medium">
                     Visualizações: {{object.visualizacoes}}
                </p>
            </div>
            <div style="...">
                <h2 class="text-gray-200 text-3xl font-medium">
                    Episodios: {{object.episodio}}
                </h2>
            
            </div>
            </div>
        </div>
    </section>

</main>
<!-- <div class="py-10">
    <h1>Esse é o detalhe do Filme: {{object.titulo}} </h1>
    <p>{{object}}</p>
    <p>{{object.descrição}}</p>
    <p>Visualizações: {{object.visualizacoes}}</p>
    <img src="{{ object.thumb.url }}">

        <h2>Episódios</h2>
        {% for episodio in object.episodios.all %}
        <a href="{{episodio.video}}">
            
            <p>Episodio {{ forloop.counter }}: {{ episodio.titulo }}  </p>
        </a>    
        {% endfor %}    
</div> -->
<!-- <div class='py-10'>
    <h2>Filmes Relacionados</h2>
    {% for filme in filmes_relacionado %}
    <p>
        <a href="{% url 'filme:detalhesfilme' filme.id %}">
            {{filme.titulo}}
        </a>
    </p>
    {% endfor %}

</div> -->
{% endblock %}

filme/templates/detalheseries.html
{% extends 'base.html' %}
{% block titulo %}
HomeSeries HasheFlix
{% endblock %}
{% load static %}

{% block content %}
<div class="py-32">
    <h1>Esse é o detalhe das Series: {{object.titulo}} </h1>
    <p>{{object}}</p>
    <p>{{object.descrição}}</p>
    <img src="{{ object.thumb.url }}">      
</div>
{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %}
{% block titulo %}
HomeFilmes HasheFlix
{% endblock %}
{% load static %}

{% block content %}
<div class="py-32">
    <h1>Essa é a nossa HomeFilmes!</h1>
    {% for filme in object_list %} 
        <hr>
        <a href="{% url 'filme:detalhesfilme' filme.id %}"><p>{{ filme }}</p></a>
        <p>{{ filme.descrição }}</p>
        <img src="{{filme.thumb.url}}" alt="" width= "200" height = 100/>>
    {% endfor %}
</div>
<div class="py-10">
    <h2>Novo</h2>
    {{lista_filmes_recentes}}
</div>
<div class="py-10">
    <h2>Em Alta</h2>
    {{lista_filmes_emalta}}
</div>
{% endblock %}

filme/templates/homepage.html
{% extends 'base.html' %}
{% block titulo %}
HomePage HasheFlix
{% endblock %}
{% load static %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat" style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
  
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

        <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
            Filmes e séries da Hashtag, tudo em um só lugar.
        </h1>
        <h3 class="text-xl md:text-xl py-5">
            Assista onde quiser. Cancele quando quiser.
        </h3>
        <h4 class="text-sm md:text-lg pb-3">
            Quer começar? Coloque seu e-mail abaixo para acessar.
        </h4>
        <div class="w-full flex justify-center">
            <div class="flex justify-center items-center w-10/12 md:w-10/12">
                <form method="post" class="w-6/12 justify-center">
                    <div class="flex flex-grow items-stretch ">
                        <input type="text" class="py-1 px-3 rounded-md text-black" placeholder="E-mail..">
                <a href="/admin">
                    <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-1 px-5 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                        <span>
                            Acessar
                        </span>
                        <ion-icon name="chevron-forward-outline" class="text-2x1"></ion-icon>
                    </button>
                </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</header>

<section class="flex flex-col md:flex-row items-center border-gray-900 border-b-8" style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
           Enjoy on you TV. 
        </h2>
        <h5 class="md:text-xl text-lg">
            Watch on smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players and more.
        </h5>
    </div>
    <div class="md:w-1/2 flex justify-center items-center">
        <img src="{%static 'images/tv.png'%}" alt="" width= "auto" height = auto/>
    </div>
</section>
<section class="flex flex-col md:flex-row items-center border-gray-900 border-b-8" style="min-height: 70vh;">
    <div class="md:w-1/2 flex justify-center items-center">
        <img src="{%static 'images/mobile-0819.jpg'%}" alt="" width= "auto" height = auto/>
    </div>
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-10">
        <h2 class="md>text-5xl text-4xl font-semibold mb-4">
            Download your shows to watch offline.
        </h2>
        <h5 class="md>text-xl text-lg">
            Save your favorites easily and always have something to watch.</br></br>Stream unlimited movies and TV programmes on your phone, tablet or
        </h5>
    </div>
</section>
<section class="flex flex-col md:flex-row items-center border-gray-900 border-b-8" style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Create Profile for kids.
        </h2>
        <h5 class="md:text-xl text-lg">
            Send kids on adventure with their favorite characters in a space made just for them-free with your membership.
        </h5>
    </div>
    <div class="md:w-1/2 flex justify-center items-center">
        <img src="{%static 'images/netflix_kid.png'%}" alt="" width= "auto" height = auto/>

    </div>
</section>

<footer class="px-5 py-10">
    <ul class="flex justify-between items-center">
        <li>2023</li>
        <li>Feito com Python (Django)</li>
        <li>by LRCORP</li>
    </ul>
</footer>

{% endblock %}

filme/templates/seriefilmes.html
{% extends 'base.html' %}
{% block titulo %}
HomeSeries HasheFlix
{% endblock %}
{% load static %}

{% block content %}

<div class="py-32">
    <h1>Essa é a nossa HomeSéries!</h1>
    {% for seriado in object_list %} 
        <hr>
        <a href="{% url 'filme:detalhesserie' seriado.id %"><p>{{ seriado }}</p></a>
        <p>{{ seriado.descrição }}</p>
        <img src="{{seriado.thumb.url}}" alt="" width= "200" height = 100/>>
    {% endfor %}
</div>

<footer class="px-5 py-10">
    <ul class="flex justify-between items-center">
        <li>2023</li>
        <li>Feito com Python (Django)</li>
        <li>by LRCORP</li>
    </ul>
</footer>
{% endblock %} 

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>
        {% block titulo %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>
    {% block head %}
    {% endblock %}
</head>
<body class="bg-black text-gray-100 font-primary">
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</body>
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
</html>

templates/navbar.html
{% load static %}

<nav class="w-full flex justify-between itens-center py-3 px-4 fixed z-50">
    <div class="w-6/12">
        <a href="/">
            <img class="w-2/12" src="{% static 'images/hashflix.png' %}"> 
            
        </a>
    </div>

    <div class="w-6/12 flex flex-nowrap justify-end">
        <div class="mr-2">
            <form>
                <input type="text" class="py-1 px-2 rounded-md text-black" placeholder="Pesquisar..">
            </form>
        </div>

        <div class="mr-2">
            <a>
                <button class="bg-red-600 tex_write py-1 px-3 rounded-md">
                    Login
                </button>
            </a>
        </div>

        <div class="mr-2">
            <div>
                <a>
                <button class="bg-red-600 tex_write py-1 px-3 rounded-md">
                    Editar Perfil
                </button>
            </a>
            </div>
        </div>
    </div>

</nav>